---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: compliance-audit-router
parameters:
  - name: "IMAGE_REGISTRY"
    displayName: "Image Registry"
    value: "quay.io"
    required: false
  - name: "IMAGE_REPOSITORY"
    displayName: "Image Repository"
    value: "app-sre"
    required: false
  - name: "IMAGE_NAME"
    displayName: "Image Name"
    value: "compliance-audit-router"
    required: false
  - name: "IMAGE_TAG"
    displayName: "Image tag"
    required: true
    value: "latest"
  - name: "IMAGE_PULL_SECRET"
    displayName: "Image Pull Secret"
    required: true
    value: "quay.io"
  - name: "JIRA_PROJECT_KEY"
    displayName: "Jira Project Key"
    required: true
  - name: "JIRA_HOST"
    displayName: "Jira service host"
    required: true
  - name: "JIRA_USERNAME"
    displayName: "Jira username"
    required: true
  - name: "JIRA_SECRET_REF_KEY"
    displayName: "Jira token secret data key"
    required: true
  - name: "SPLUNK_HOST"
    displayName: "Splunk service host"
    required: true
  - name: "SPLUNK_SECRET_REF_KEY"
    displayName: "Splunk token secret data key"
    required: true
  - name: "JIRA_SECRET_REF_NAME"
    displayName: "Jira token name"
    required: true
  - name: "SPLUNK_SECRET_REF_NAME"
    displayName: "Splunk token name"
    required: true
  - name: "REPLICAS"
    displayName: "Number of Deployment replicas"
    value: "2"
    required: false
  - name: "REQUESTS_CPU"
    displayName: "CPU Requests"
    value: "300m"
    required: false
  - name: "REQUESTS_MEM"
    displayName: "Memory Requests"
    value: "2Gi"
    required: false
  - name: "LIMITS_MEM"
    displayName: "Memory Limits"
    value: "2Gi"
    required: false
  - name: "LISTEN_PORT"
    displayName: "Port to listen on"
    value: "8080"
    required: false
  - name: "DRYRUN"
    displayName: "Dry-run mode"
    value: "true"
    required: false
  - name: "VERBOSE"
    displayName: "Verbose output"
    value: "true"
    required: false
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: compliance-audit-router
      labels:
        app: compliance-audit-router
    spec:
      selector:
        matchLabels:
          app: compliance-audit-router
      template:
        metadata:
          labels:
            app: compliance-audit-router
        spec:
          containers:
            - name: compliance-audit-router
              # yamllint disable-line rule:line-length
              image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: "${{LISTEN_PORT}}"
                  protocol: TCP
              env:
                - name: CAR_VERBOSE
                  value: ${VERBOSE}
                - name: CAR_DRYRUN
                  value: ${DRYRUN}
                - name: CAR_JIRACONFIG_KEY
                  value: ${JIRA_PROJECT_KEY}
                - name: CAR_JIRACONFIG_HOST
                  value: ${JIRA_HOST}
                - name: CAR_JIRA_USERNAME
                  value: ${JIRA_USERNAME}
                - name: CAR_JIRACONFIG_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: ${JIRA_SECRET_REF_KEY}
                      name: ${JIRA_SECRET_REF_NAME}
                - name: CAR_SPLUNKCONFIG_HOST
                  value: ${SPLUNK_HOST}
                - name: CAR_SPLUNKCONFIG_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: ${SPLUNK_SECRET_REF_KEY}
                      name: ${SPLUNK_SECRET_REF_NAME}
              resources:
                limits:
                  memory: ${LIMITS_MEM}
                requests:
                  cpu: ${REQUESTS_CPU}
                  memory: ${REQUESTS_MEM}
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: "${{LISTEN_PORT}}"
                initialDelaySeconds: 5
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: "${{LISTEN_PORT}}"
                initialDelaySeconds: 5
                periodSeconds: 5
          imagePullSecrets:
            - name: ${IMAGE_PULL_SECRET}
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 3
      progressDeadlineSeconds: 300
  - apiVersion: v1
    kind: Service
    metadata:
      name: compliance-audit-router
      labels:
        app: compliance-audit-router
    spec:
      selector:
        app: compliance-audit-router
      ports:
          # LISTEN_PORT must be in quotes to be parsed properly as an integer
        - port: "${{LISTEN_PORT}}"
          targetPort: "${{LISTEN_PORT}}"
          protocol: TCP
