---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: compliance-audit-router
parameters:
  - name: "IMAGE_REGISTRY"
    displayName: "Image Registry"
    value: "quay.io"
    required: false
  - name: "IMAGE_REPOSITORY"
    displayName: "Image Repository"
    value: "app-sre"
    required: false
  - name: "IMAGE_NAME"
    displayName: "Image Name"
    value: "compliance-audit-router"
    required: false
  - name: "IMAGE_TAG"
    displayName: "Image tag"
    required: true
    value: "latest"
  - name: "IMAGE_PULL_SECRET"
    displayName: "Image Pull Secret"
    required: true
    value: "quay.io"
  - name: "JIRA_SECRET_REF_KEY"
    displayName: "Jira token secret data key"
    required: true
  - name: "SPLUNK_SECRET_REF_KEY"
    displayName: "Splunk token secret data key"
    required: true
  - name: "JIRA_SECRET_REF_NAME"
    displayName: "Jira token name"
    required: true
  - name: "SPLUNK_SECRET_REF_NAME"
    displayName: "Splunk token name"
    required: true
  - name: "REPLICAS"
    displayName: "Number of Deployment replicas"
    value: "2"
    required: false
  - name: "REQUESTS_CPU"
    displayName: "CPU Requests"
    value: "300m"
    required: false
  - name: "REQUESTS_MEM"
    displayName: "Memory Requests"
    value: "2Gi"
    required: false
  - name: "LIMITS_MEM"
    displayName: "Memory Limits"
    value: "2Gi"
    required: false
  - name: "LISTEN_PORT"
    displayName: "Port to listen on"
    value: "8080"
    required: false
  - name: "DRYRUN"
    displayName: "Dry-run mode"
    value: "true"
    required: false
  - name: "VERBOSE"
    displayName: "Verbose output"
    value: "true"
    required: false
  # This is the FOO part of FOO.apps.mycluster.com
  - name: "ROUTE_HOSTNAME"
    displayName: "Hostname for the incoming route (not fully qualified)"
    required: true
  # This is the apps.mycluster.com part of FOO.apps.mycluster.com
  - name: "ROUTE_CLUSTER_DOMAIN"
    displayName: "Cluster *apps domain (fully qualified)"
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: compliance-audit-router
      labels:
        app: compliance-audit-router
    spec:
      replicas: ${{REPLICAS}}
      selector:
        matchLabels:
          app: compliance-audit-router
      template:
        metadata:
          labels:
            app: compliance-audit-router
        spec:
          containers:
            - name: compliance-audit-router
              imagePullPolicy: Always
              imagePullSecret: ${IMAGE_PULL_SECRET}
              # yamllint disable-line rule:line-length
              image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}
              env:
                - name: CAR_VERBOSE
                  value: ${VERBOSE}
                - name: CAR_DRYRUN
                  value: ${DRYRUN}
                - name: CAR_JIRACONFIG_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ${JIRA_SECRET_REF_NAME}
                      key: ${JIRA_SECRET_REF_KEY}
                - name: CAR_SPLUNKCONFIG_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ${SPLUNK_SECRET_REF_NAME}
                      key: ${SPLUNK_SECRET_REF_KEY}
              resources:
                requests:
                  cpu: ${REQUESTS_CPU}
                  memory: ${REQUESTS_MEM}
                limits:
                  memory: ${LIMITS_MEM}
  - apiVersion: v1
    kind: Service
    metadata:
      name: compliance-audit-router
      labels:
        app: compliance-audit-router
    spec:
      selector:
        app: compliance-audit-router
      ports:
        - protocol: TCP
          port: ${LISTEN_PORT}
          targetPort: ${LISTEN_PORT}
